import type { Location } from './types';

export const MAP_POINTS: Location[] = [
  { id: 1, name: "Câmpus Florianópolis", region: "Grande Fpolis", description: "Principal campus da instituição, oferecendo uma vasta gama de cursos técnicos e superiores, com forte ênfase em inovação e pesquisa.", position: { top: "48%", left: "89%" } },
  { id: 2, name: "Câmpus São José", region: "Grande Fpolis", description: "Polo de telecomunicações e engenharia de refrigeração, com laboratórios modernos para formação de profissionais da área de tecnologia.", position: { top: "50%", left: "87%" } },
  { id: 3, name: "Câmpus Jaraguá do Sul-Centro", region: "Norte", description: "Oferece cursos nas áreas de mecânica industrial, eletrotécnica e desenvolvimento de sistemas, em parceria com a indústria local.", position: { top: "25%", left: "80%" } },
  { id: 4, name: "Câmpus Florianópolis-Continente", region: "Grande Fpolis", description: "Especializado em gastronomia, hotelaria e turismo, é um centro de formação profissional para o setor de serviços da capital.", position: { top: "52%", left: "87.5%" } },
  { id: 5, name: "Câmpus Araranguá", region: "Sul", description: "Polo de tecnologia da informação e comunicação, com cursos voltados para o desenvolvimento de software e design digital no extremo sul catarinense.", position: { top: "86%", left: "83%" } },
  { id: 6, name: "Câmpus Joinville", region: "Norte", description: "Grande polo de engenharia, com cursos de mecânica, eletroeletrônica e plásticos, integrado ao maior polo industrial do estado.", position: { top: "18%", left: "86%" } },
  { id: 7, name: "Câmpus Chapecó", region: "Oeste", description: "Centro de excelência em tecnologia de alimentos e engenharia de controle e automação, vital para o polo agroindustrial do oeste.", position: { top: "42%", left: "24%" } },
  { id: 8, name: "Câmpus São Miguel do Oeste", region: "Oeste", description: "Referência em agroindústria e ciências da computação, este campus na fronteira fomenta a inovação no setor alimentício.", position: { top: "33%", left: "12%" } },
  { id: 9, name: "Câmpus Canoinhas", region: "Norte", description: "Especializado em agronegócio e engenharia florestal, desenvolvendo tecnologias para a indústria madeireira e agrícola do Planalto Norte.", position: { top: "15%", left: "58%" } },
  { id: 10, name: "Câmpus Criciúma", region: "Sul", description: "Referência em engenharia mecatrônica e design, apoiando a forte indústria de cerâmica e vestuário da região sul.", position: { top: "80%", left: "80%" } },
  { id: 11, name: "Câmpus Gaspar", region: "Vale do Itajaí", description: "Polo da indústria têxtil e de confecção, com cursos de design de moda, modelagem e processos têxteis.", position: { top: "43%", left: "81%" } },
  { id: 12, name: "Câmpus Lages", region: "Planalto Serrano", description: "Centro de biotecnologia e ciências agrárias, desenvolvendo pesquisas para o agronegócio e a pecuária na serra catarinense.", position: { top: "60%", left: "55%" } },
  { id: 13, name: "Câmpus Itajaí", region: "Vale do Itajaí", description: "Focado em logística, comércio exterior e engenharia naval, atendendo às demandas do complexo portuário de Itajaí.", position: { top: "44%", left: "86%" } },
  { id: 14, name: "Câmpus Palhoça Bilíngue", region: "Grande Fpolis", description: "Primeiro campus público bilíngue (Libras/Português) do Brasil, focado na inclusão e acessibilidade, com cursos de comunicação e tradução.", position: { top: "55%", left: "86%" } },
  { id: 15, name: "Câmpus Xanxerê", region: "Oeste", description: "Polo de engenharia mecânica e agroindústria, contribuindo para a inovação e o fortalecimento da economia regional.", position: { top: "38%", left: "33%" } },
  { id: 16, name: "Câmpus Caçador", region: "Oeste", description: "Focado em engenharia de produção e automação industrial, este campus colabora com as indústrias da região meio-oeste.", position: { top: "30%", left: "48%" } },
  { id: 17, name: "Câmpus Urupema", region: "Planalto Serrano", description: "Focado em vitivinicultura e fruticultura de clima temperado, aproveitando as condições climáticas únicas da cidade mais fria do Brasil.", position: { top: "70%", left: "63%" } },
  { id: 18, name: "Câmpus Jaraguá do Sul-Rau", region: "Norte", description: "Com foco em vestuário, química e design, este campus atende à diversificada matriz industrial da região norte.", position: { top: "23%", left: "82%" } },
  { id: 19, name: "Câmpus Garopaba", region: "Sul", description: "Voltado para gestão ambiental e desenvolvimento sustentável, com projetos focados na preservação do ecossistema litorâneo.", position: { top: "67%", left: "89%" } },
  { id: 20, name: "Câmpus Tubarão", region: "Sul", description: "Com cursos de eletrotécnica e automação industrial, o campus atende às necessidades do parque industrial da região.", position: { top: "78%", left: "84%" } },
  { id: 21, name: "Câmpus São Carlos", region: "Oeste", description: "Especializado em agroecologia e desenvolvimento de sistemas, promove práticas agrícolas sustentáveis na região.", position: { top: "48%", left: "20%" } },
  { id: 22, name: "Câmpus São Lourenço do Oeste", region: "Oeste", description: "Oferece cursos voltados para a administração e o agronegócio, impulsionando o desenvolvimento socioeconômico local.", position: { top: "28%", left: "28%" } },
  { id: 23, name: "Câmpus Tijucas", region: "Grande Fpolis", description: "Novo campus focado em construção civil e logística, atendendo a uma região de grande crescimento industrial.", position: { top: "48%", left: "87%" } }
];